const ZH_CN_DATA_COPY = {
  data: {
    title: "数据",
    subtitle: "浏览长期活动趋势",
    pastSevenDays: "近 7 天",
    activityTrend: "活动趋势",
    weeklyTotal: "7 日总时长",
    dailyAverage: "日均时长",
    appTrend: "应用趋势",
    appSearchPlaceholder: "搜索应用",
    appTrendAppList: "应用列表",
    appTrendEmpty: "当前范围暂无应用记录",
    appTrendNoMatch: "没有匹配的应用",
    appTrendTotal: "总时长",
    appTrendAverage: "日均",
    appTrendActiveDays: "活跃天数",
    appTrendPeakDay: "峰值日",
    appTrendUsage: "应用时长",
    appHeatmap: "应用热力图",
    webHeatmap: "网页热力图",
    interactionHint: "双击详情 · Ctrl 多选",
    selectionLimitReached: "最多同时比较 7 项",
    selectionLastItem: "至少保留 1 项",
    selectedObjectCount: (count: number) => `${count} 个对象`,
    destinationApp: "应用",
    destinationWeb: "网页",
    destinationMode: "选择时间去向类型",
    webTrend: "网页趋势",
    webSearchPlaceholder: "搜索网页",
    webTrendDomainList: "网页列表",
    webTrendEmpty: "当前范围暂无网页记录",
    webTrendNoMatch: "没有匹配的网页",
    webTrendTotal: "总时长",
    webTrendUsage: "网页记录时长",
    webTrendError: "网页分析暂时不可用",
    webTrendRefreshError: "更新失败，显示上次结果",
    webTrendUpdating: "更新中",
    webTrendRetry: "重试",
    activityHeatmap: "活动热力图",
    activityHeatmapHint: "每日活动强度",
    heatmapDaily: "每日",
    heatmapWeekly: "每周",
    webNotRecorded: "未记录",
    webNoActivity: "未记录到网页活动",
    recentYear: "近一年",
    pastThirtyDays: "近 30 天",
    rangePickerTitle: "选择范围",
    pickerModes: {
      custom: "自定义",
      week: "一周",
      month: "一月",
      year: "一年",
    },
    pickStartDate: "开始日期",
    pickEndDate: "结束日期",
    pickDate: "选择日期",
    shortRangeHint: "当前范围少于 7 天。",
    applyRange: "确定",
    customDayCount: (days: number) => `${days}天`,
    weekLabel: (week: number) => `${week}周`,
    yearLabel: (year: number) => `${year}年`,
    rangeTotal: (label: string) => `${label}总时长`,
    yearlyAverage: "月均时长",
    yearlyAverageHint: "按近一年月份计算",
    rangeAverageHint: (rangeLabel: string) => `按${rangeLabel}计算`,
    notStarted: "未开始",
    duration: "时长",
    monthlyAverage: "月均",
  },
};

const EN_US_DATA_COPY = {
  data: {
    title: "Data",
    subtitle: "Browse long-term trends",
    pastSevenDays: "Last 7 days",
    activityTrend: "Activity Trend",
    weeklyTotal: "7-day total",
    dailyAverage: "Daily avg.",
    appTrend: "App Trends",
    appSearchPlaceholder: "Search apps",
    appTrendAppList: "App list",
    appTrendEmpty: "No app data in this range",
    appTrendNoMatch: "No matching apps",
    appTrendTotal: "Total",
    appTrendAverage: "Daily avg.",
    appTrendActiveDays: "Active days",
    appTrendPeakDay: "Peak day",
    appTrendUsage: "App time",
    appHeatmap: "App Heatmap",
    webHeatmap: "Web Heatmap",
    interactionHint: "Double-click details · Ctrl select",
    selectionLimitReached: "Compare up to 7 items",
    selectionLastItem: "Keep at least 1 item selected",
    selectedObjectCount: (count: number) => `${count} ${count === 1 ? "item" : "items"}`,
    destinationApp: "Apps",
    destinationWeb: "Web",
    destinationMode: "Select time destination type",
    webTrend: "Web Trends",
    webSearchPlaceholder: "Search websites",
    webTrendDomainList: "Website list",
    webTrendEmpty: "No web records in this range",
    webTrendNoMatch: "No matching websites",
    webTrendTotal: "Total",
    webTrendUsage: "Web recorded time",
    webTrendError: "Web analysis is temporarily unavailable",
    webTrendRefreshError: "Update failed. Showing the last result.",
    webTrendUpdating: "Updating",
    webTrendRetry: "Retry",
    activityHeatmap: "Activity Heatmap",
    activityHeatmapHint: "Daily activity intensity",
    heatmapDaily: "Daily",
    heatmapWeekly: "Weekly",
    webNotRecorded: "Not recorded",
    webNoActivity: "No web activity recorded",
    recentYear: "Past year",
    pastThirtyDays: "Last 30 days",
    rangePickerTitle: "Select range",
    pickerModes: {
      custom: "Custom",
      week: "Week",
      month: "Month",
      year: "Year",
    },
    pickStartDate: "Start date",
    pickEndDate: "End date",
    pickDate: "Select date",
    shortRangeHint: "The current range is shorter than 7 days.",
    applyRange: "Apply",
    customDayCount: (days: number) => `${days} days`,
    weekLabel: (week: number) => `Week ${week}`,
    yearLabel: (year: number) => String(year),
    rangeTotal: (label: string) => `${label} total`,
    yearlyAverage: "Monthly avg.",
    yearlyAverageHint: "Based on months in the past year",
    rangeAverageHint: (rangeLabel: string) => `Based on ${rangeLabel}`,
    notStarted: "Not started",
    duration: "Duration",
    monthlyAverage: "Monthly avg.",
  },
};

export const dataCopy = {
  "zh-CN": ZH_CN_DATA_COPY,
  "en-US": EN_US_DATA_COPY,
} as const;
