const ZH_CN_EXPORT_COPY = {
  export: {
    title: "数据导出",
    subtitle: "导出会话和网页活动，用于表格查看、归档或分析。",
    sidebarDescription: "导出",
    dialogDescription: "选择范围、格式和字段后开始导出。",
    timeRangeLabel: "时间范围",
    timeRangePresetToday: "本日",
    timeRangePresetThisWeek: "本周",
    timeRangePresetThisMonth: "本月",
    timeRangePresetThisYear: "本年",
    timeRangePresetCustom: "自定义",
    timeRangeModeDay: "本日",
    timeRangeModeWeek: "本周",
    timeRangeModeMonth: "本月",
    timeRangeModeYear: "本年",
    previousRange: "上一个范围",
    nextRange: "下一个范围",
    openRangePicker: "打开范围选择",
    previousPickerMode: "上一个范围模式",
    nextPickerMode: "下一个范围模式",
    timeRangeCustomStart: "开始日期",
    timeRangeCustomEnd: "结束日期",
    timeRangeMissing: "请选择开始日期和结束日期",
    timeRangeInvalid: "结束日期不能早于开始日期",
    formatLabel: "导出格式",
    formatCSV: "CSV",
    formatSQLite: "SQLite",
    formatParquet: "Parquet",
    formatMarkdown: "Markdown",
    formatCSVHint: "适合 Excel 与通用表格处理。",
    formatSQLiteHint: "适合本地 SQL 查询和完整归档。",
    formatParquetHint: "适合分析工具与列式处理。",
    formatMarkdownHint: "适合直接阅读、编辑和笔记整理。",
    exportAction: "导出",
    exporting: "导出中...",
    exportDone: (count: number) => `已导出 ${count} 条记录`,
    exportFailed: "导出失败",
    configFields: "配置字段",
    configFieldsTitle: "导出字段配置",
    configFieldsHint: "勾选需要导出的字段。",
    configFieldsCount: (n: number, total: number) => `${n} / ${total} 个字段`,
    configFieldsEmpty: "至少保留一个导出字段",
    restoreFormatDefaults: "恢复当前格式默认字段",
    groupActivity: "活动基础",
    groupActivityHint: "记录类型、时间和时长等共同字段。",
    groupApps: "应用信息",
    groupAppsHint: "来自本地应用会话的字段。",
    groupWeb: "网页信息",
    groupWebHint: "来自浏览器网页活动的字段。",
    groupClassification: "分类信息",
    groupClassificationHint: "当前分类名称、标识与颜色。",
    groupAnalysis: "时间分析",
    groupAnalysisHint: "用于按周、月等周期分析。",
    groupAudit: "来源与审计",
    groupAuditHint: "来源标识与记录写入时间。",
    toggleField: "切换字段导出状态",
    selectGroupFields: "全选",
    deselectGroupFields: "取消全选",
    collapseFieldGroup: "折叠",
    expandFieldGroup: "展开",
    fields: {
      record_type: { label: "记录类型", desc: "标记来自本地应用(session)还是网页浏览(web)" },
      category: { label: "分类", desc: "按当前应用/域名分类规则计算出的分类名称" },
      exe_name: { label: "可执行文件名", desc: "进程的可执行文件名称，如 chrome.exe" },
      app_name: { label: "应用名称", desc: "应用程序的显示名称，如 Google Chrome" },
      window_title: { label: "窗口标题", desc: "活动窗口的标题文字" },
      domain: { label: "域名", desc: "网页访问的域名，如 www.google.com" },
      normalized_domain: { label: "标准化域名", desc: "去除 www 前缀后的标准化域名" },
      url: { label: "URL 地址", desc: "网页的完整 URL 地址" },
      page_title: { label: "页面标题", desc: "网页的 HTML 标题" },
      start_time: { label: "开始时间", desc: "记录开始时间，格式 YYYY-MM-DD HH:mm:ss" },
      end_time: { label: "结束时间", desc: "记录结束时间，格式 YYYY-MM-DD HH:mm:ss" },
      duration_ms: { label: "时长（毫秒）", desc: "精确记录时长，单位毫秒" },
      category_id: { label: "分类 ID", desc: "当前分类的稳定 ID，可用于后续关联" },
      local_date: { label: "本地日期", desc: "按开始时间换算的本地日期" },
      local_week: { label: "本地周", desc: "按 ISO 周规则生成的本地周" },
      local_month: { label: "本地月份", desc: "按开始时间生成的 YYYY-MM" },
      weekday: { label: "星期", desc: "星期数字，1 表示周一，7 表示周日" },
      start_hour: { label: "开始小时", desc: "开始时间所在小时，0-23" },
      duration_minutes: { label: "时长（分钟）", desc: "便于分析的分钟值，保留三位小数" },
      source_key: { label: "来源键", desc: "应用为 exe，网页为标准化域名" },
      source_name: { label: "来源名称", desc: "应用名称或网页域名显示名" },
      session_id: { label: "会话 ID", desc: "本地应用会话记录 ID" },
      web_segment_id: { label: "网页片段 ID", desc: "网页活动片段记录 ID" },
      continuity_group_start_time: { label: "连续组开始时间", desc: "会话连续组开始时间" },
      browser_client_id: { label: "浏览器客户端 ID", desc: "网页同步来源客户端 ID" },
      browser_kind: { label: "浏览器类型", desc: "浏览器家族标识，如 chrome/firefox" },
      browser_exe_name: { label: "浏览器可执行文件", desc: "浏览器进程可执行文件名" },
      favicon_url: { label: "网站图标 URL", desc: "网页活动记录中的 favicon 地址" },
      web_source: { label: "网页来源", desc: "网页活动写入来源" },
      created_at: { label: "创建时间", desc: "网页活动记录创建时间" },
      updated_at: { label: "更新时间", desc: "网页活动记录更新时间" },
      category_color: { label: "分类颜色", desc: "当前分类颜色值" },
    },
  },
};

const EN_US_EXPORT_COPY = {
  export: {
    title: "Data Export",
    subtitle: "Export sessions and web activity for spreadsheets, archives, or analysis.",
    sidebarDescription: "Export",
    dialogDescription: "Choose the range, format, and fields before exporting.",
    timeRangeLabel: "Time range",
    timeRangePresetToday: "Today",
    timeRangePresetThisWeek: "This week",
    timeRangePresetThisMonth: "This month",
    timeRangePresetThisYear: "This year",
    timeRangePresetCustom: "Custom",
    timeRangeModeDay: "Today",
    timeRangeModeWeek: "This week",
    timeRangeModeMonth: "This month",
    timeRangeModeYear: "This year",
    previousRange: "Previous range",
    nextRange: "Next range",
    openRangePicker: "Open range picker",
    previousPickerMode: "Previous range mode",
    nextPickerMode: "Next range mode",
    timeRangeCustomStart: "Start date",
    timeRangeCustomEnd: "End date",
    timeRangeMissing: "Choose both a start date and an end date",
    timeRangeInvalid: "End date cannot be earlier than start date",
    formatLabel: "Format",
    formatCSV: "CSV",
    formatSQLite: "SQLite",
    formatParquet: "Parquet",
    formatMarkdown: "Markdown",
    formatCSVHint: "Best for Excel and general spreadsheet work.",
    formatSQLiteHint: "Best for local SQL queries and complete archives.",
    formatParquetHint: "Best for analytics tools and columnar processing.",
    formatMarkdownHint: "Best for reading, editing, and organizing notes.",
    exportAction: "Export",
    exporting: "Exporting...",
    exportDone: (count: number) => `Exported ${count} records`,
    exportFailed: "Export failed",
    configFields: "Configure Fields",
    configFieldsTitle: "Export Field Configuration",
    configFieldsHint: "Select the fields to export.",
    configFieldsCount: (n: number, total: number) => `${n} / ${total} fields`,
    configFieldsEmpty: "Keep at least one export field",
    restoreFormatDefaults: "Restore defaults for this format",
    groupActivity: "Activity basics",
    groupActivityHint: "Shared record type, time, and duration fields.",
    groupApps: "App information",
    groupAppsHint: "Fields from local application sessions.",
    groupWeb: "Web information",
    groupWebHint: "Fields from browser activity records.",
    groupClassification: "Classification",
    groupClassificationHint: "Current category name, identity, and color.",
    groupAnalysis: "Time analysis",
    groupAnalysisHint: "Fields for weekly and monthly analysis.",
    groupAudit: "Source and audit",
    groupAuditHint: "Source identity and record write times.",
    toggleField: "Toggle field export state",
    selectGroupFields: "Select all",
    deselectGroupFields: "Deselect all",
    collapseFieldGroup: "Collapse",
    expandFieldGroup: "Expand",
    fields: {
      record_type: { label: "Record Type", desc: "session (local app) or web (browsing)" },
      category: { label: "Category", desc: "Category name computed from current app/domain rules" },
      exe_name: { label: "Executable Name", desc: "Process executable filename, e.g. chrome.exe" },
      app_name: { label: "App Name", desc: "Display name of the application, e.g. Google Chrome" },
      window_title: { label: "Window Title", desc: "Active window title text" },
      domain: { label: "Domain", desc: "Website domain, e.g. www.google.com" },
      normalized_domain: { label: "Normalized Domain", desc: "Domain with www prefix stripped" },
      url: { label: "URL", desc: "Full URL of the page" },
      page_title: { label: "Page Title", desc: "HTML title of the page" },
      start_time: { label: "Start Time", desc: "Record start time (YYYY-MM-DD HH:mm:ss)" },
      end_time: { label: "End Time", desc: "Record end time (YYYY-MM-DD HH:mm:ss)" },
      duration_ms: { label: "Duration (ms)", desc: "Record duration in milliseconds" },
      category_id: { label: "Category ID", desc: "Stable current category ID for joins" },
      local_date: { label: "Local Date", desc: "Local date derived from start time" },
      local_week: { label: "Local Week", desc: "ISO local week derived from start time" },
      local_month: { label: "Local Month", desc: "YYYY-MM derived from start time" },
      weekday: { label: "Weekday", desc: "Weekday number, 1 is Monday and 7 is Sunday" },
      start_hour: { label: "Start Hour", desc: "Start hour, 0-23" },
      duration_minutes: { label: "Duration (minutes)", desc: "Record duration in minutes" },
      source_key: { label: "Source Key", desc: "Executable for apps, normalized domain for web" },
      source_name: { label: "Source Name", desc: "App name or web domain display name" },
      session_id: { label: "Session ID", desc: "Local app session row ID" },
      web_segment_id: { label: "Web Segment ID", desc: "Web activity segment row ID" },
      continuity_group_start_time: { label: "Continuity Group Start", desc: "Start time of the session continuity group" },
      browser_client_id: { label: "Browser Client ID", desc: "Web sync source client ID" },
      browser_kind: { label: "Browser Kind", desc: "Browser family, such as chrome/firefox" },
      browser_exe_name: { label: "Browser Executable", desc: "Browser process executable name" },
      favicon_url: { label: "Favicon URL", desc: "Favicon URL stored with the web activity record" },
      web_source: { label: "Web Source", desc: "Source that wrote the web activity record" },
      created_at: { label: "Created At", desc: "Web activity record creation time" },
      updated_at: { label: "Updated At", desc: "Web activity record update time" },
      category_color: { label: "Category Color", desc: "Current category color value" },
    },
  },
};

export const exportCopy = {
  "zh-CN": ZH_CN_EXPORT_COPY,
  "en-US": EN_US_EXPORT_COPY,
} as const;
