import assert from "node:assert/strict";
import { groupWebCandidates, refreshKnownWebDomains, resolveWebOwner, setWebDomainIndependent, webGroupKey, webGroupIcon } from "../src/shared/classification/webLinks.ts";
import { buildClassificationDraftChangePlan, cloneClassificationDraftState, hasClassificationDraftChanges } from "../src/features/classification/services/classificationDraftState.ts";
import { buildCommitDraftChangePlanSettingMutations } from "../src/features/classification/services/classificationStore.ts";
import { deleteCategoryFromDraftState, updateWebDomainOverrideInDraftState } from "../src/features/classification/hooks/appMappingStateHelpers.ts";
import { buildWebDomainDistribution, buildWebDomainIconMap } from "../src/features/history/services/historyWebActivityViewModel.ts";
import { webLinksOverrides, parseWebLinksSnapshot } from "../src/platform/persistence/webLinksGateway.ts";
import type { WebActivitySegment } from "../src/shared/types/webActivity.ts";

const domains = ['chat.deepseek.com','platform.deepseek.com','www.deepseek.com','deepseek.com'];
const key = webGroupKey('deepseek.com');
const snapshot = { domains, rules: {}, overrides: {}, roots: Object.fromEntries(domains.map(d=>[d,'deepseek.com'])),
  totals: Object.fromEntries(domains.map((d,i)=>[d,[30000,5000,10000,2000][i]])),
  favicons: Object.fromEntries(domains.map(d=>[d,'https://'+d+'/favicon.ico'])) };
const raw = webLinksOverrides(parseWebLinksSnapshot(snapshot));
const noRootCards = groupWebCandidates([], webLinksOverrides({ ...snapshot, domains: domains.slice(0, 3) }));
assert.equal(noRootCards.length, 1);
assert.equal(noRootCards[0].domain, 'deepseek.com');
assert.equal(noRootCards[0].memberCandidates?.length, 3);
assert.equal(noRootCards[0].memberCandidates?.some(member => member.domain === 'deepseek.com'), false);
assert.equal(noRootCards[0].totalDuration, 45000);
const cards=groupWebCandidates([],raw);
assert.equal(cards.length,1);
assert.equal(cards[0].domain,'deepseek.com');
assert.deepEqual(cards[0].memberCandidates?.map(m=>m.domain), [...domains].sort());
assert.equal(cards[0].totalDuration,47000);
assert.equal(cards[0].faviconUrl,snapshot.favicons[domains[0]]);
const equalIcons = webLinksOverrides({...snapshot,totals:Object.fromEntries(domains.map(domain=>[domain,1000]))});
assert.equal(webGroupIcon(key,equalIcons),snapshot.favicons['chat.deepseek.com']);
assert.equal(webGroupIcon(key,Object.fromEntries(Object.entries(equalIcons).reverse())),webGroupIcon(key,equalIcons));
const missingIcon = {...raw,[domains[0]]:{...raw[domains[0]],faviconUrl:''}};
assert.equal(webGroupIcon(key,missingIcon),snapshot.favicons['www.deepseek.com']);
assert.equal(webGroupIcon(key,{...missingIcon,'www.deepseek.com':{...missingIcon['www.deepseek.com'],knownDomain:false}}),snapshot.favicons['platform.deepseek.com']);
assert.equal(resolveWebOwner('deepseek.com',raw),key);
assert.equal(resolveWebOwner('127.0.0.1',raw),'127.0.0.1');
const saved={overrides:{},webDomainOverrides:raw,categoryColorOverrides:{},categoryLabelOverrides:{},persistedCategoryIds:[],deletedCategories:[]};
const categorized = cloneClassificationDraftState(saved);
categorized.webDomainOverrides[domains[0]].category = 'development';
const categoryDeleted = deleteCategoryFromDraftState(categorized, 'development');
assert.equal(resolveWebOwner(domains[0], categoryDeleted.webDomainOverrides), key);
assert.equal(webGroupIcon(key, categoryDeleted.webDomainOverrides), snapshot.favicons[domains[0]]);
const change=setWebDomainIndependent('chat.deepseek.com',true,raw)!;
const draft=updateWebDomainOverrideInDraftState(saved,change.key,change.override);
assert.equal(hasClassificationDraftChanges(saved,draft),true);
assert.equal(resolveWebOwner('chat.deepseek.com',draft.webDomainOverrides),'chat.deepseek.com');
assert.equal(resolveWebOwner('platform.deepseek.com',draft.webDomainOverrides),key);
assert.equal(webGroupIcon(key,draft.webDomainOverrides),snapshot.favicons['www.deepseek.com']);
assert.equal(groupWebCandidates([],draft.webDomainOverrides).length,2);
const copy=cloneClassificationDraftState(draft);
copy.webDomainOverrides[key].siteRule!.exceptions.push('www.deepseek.com');
assert.deepEqual(draft.webDomainOverrides[key].siteRule!.exceptions,['chat.deepseek.com']);
const mutations=buildCommitDraftChangePlanSettingMutations(buildClassificationDraftChangePlan(saved,draft));
assert.deepEqual(JSON.parse(mutations[0].value!),{previous:null,next:{version:2,exceptions:['chat.deepseek.com']}});
assert.equal(mutations[0].key,'__web_site::deepseek.com');
const merge=setWebDomainIndependent('chat.deepseek.com',false,draft.webDomainOverrides)!;
const restored=updateWebDomainOverrideInDraftState(draft,merge.key,merge.override);
assert.equal(hasClassificationDraftChanges(saved,restored),false);
const rootChange=setWebDomainIndependent('deepseek.com',true,raw)!;
const rootDraft={...raw,[key]:rootChange.override};
assert.equal(resolveWebOwner('deepseek.com',rootDraft),'deepseek.com');
assert.equal(resolveWebOwner('www.deepseek.com',rootDraft),key);
assert.equal(groupWebCandidates([],rootDraft).filter(c=>c.domain==='deepseek.com').length,2);
const future=webLinksOverrides({...snapshot,domains:[...domains,'new.deepseek.com'],roots:{...snapshot.roots,'new.deepseek.com':'deepseek.com'}});
const refreshed=refreshKnownWebDomains(draft.webDomainOverrides,future);
assert.equal(resolveWebOwner('new.deepseek.com',refreshed),key);
assert.equal(resolveWebOwner('chat.deepseek.com',refreshed),'chat.deepseek.com');
const deleted=refreshKnownWebDomains(raw,webLinksOverrides({...snapshot,domains:[],roots:{},totals:{},favicons:{}}));
assert.deepEqual(groupWebCandidates([],deleted),[]);
const segments:WebActivitySegment[]=domains.map((domain,i)=>({id:i+1,browserClientId:'fixture',browserKind:'chrome',browserExeName:'chrome.exe',domain,normalizedDomain:domain,url:'https://'+domain,title:null,faviconUrl:null,startTime:1000+i*10000,endTime:6000+i*10000,duration:5000}));
const range={startMs:0,endMs:60000};
assert.equal(buildWebDomainIconMap([segments[1]],raw,{})[key],snapshot.favicons[domains[0]],'a day without the longest-used member still uses its global icon');
const before=buildWebDomainDistribution(segments,range,60000,raw);
const after=buildWebDomainDistribution(segments,range,60000,draft.webDomainOverrides);
assert.equal(before.reduce((s,r)=>s+r.duration,0),after.reduce((s,r)=>s+r.duration,0));
assert.equal(before[0].label,'deepseek.com');
assert.equal(before[0].faviconUrl,snapshot.favicons[domains[0]]);
assert.throws(()=>parseWebLinksSnapshot({...snapshot,rules:{'deepseek.com':{members:[]}}}),/Invalid website rule/);
assert.throws(()=>parseWebLinksSnapshot({...snapshot,roots:null}),/metadata/);
console.log('Automatic web grouping: exact exceptions, root identity, icons, drafts, persistence, deletion refresh and conservation passed');
